<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DryCastResinSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('dry_cast_resins')->insert([
            'kd_manhour' => '1',
            'nama_product' => 'Dry Cast Resin',
            'kategori' => '5',
            'nomor_so' => 'SO/TEST',
            'id_fg' => 'FG/TEST',
            'ukuran_kapasitas' => '10',
            'total_hour' => '100',
            'manhour_id' => null,
            'coil_lv' => 'FLAT-KONDUKTOR 1',
            'coil_hv' => 'FLAT-KONDUKTOR 1',
            'potong_leadwire' => 'TEBAL RAIL COPPER = 10T',
            'potong_isolasi' => 'DOG BONE,INNER,OUTER,GANJAL ANTAR SECTION',
            'hv_moulding' => 'KONDUKTOR 1',
            'hv_casting' => '1X PENGISIAN',
            'hv_demoulding' => 'PAKAI AIRWAY STICK',
            'lv_bobbin' => 'PENGECATAN COIL LV & CURING,BUKA BOBIN LV',
            'lv_moulding' => 'SETTING MOULD,MOULDING,CASTING 1 X PROSES PENGISIAN,CASTING 2 X PROSES PENGISIAN',
            'touch_up' => 'HV,LV',
            'type_susun_core' => 'STACKING OUTSOURCHING',
            'wiring' => 'NON-COMPLETE',
            'instal_housing' => 'DENGAN BASE',
            'bongkar_housing' => 'DENGAN BASE',
            'pembuatan_cu_link' => 'HV / LV (STANDARD)',
            'others' => 'PEMBUATAN CU BAR,PEMBUATAN KONEKSI HV,ASSEMBLY,FINISHING',
            'accesories' => 'FAN,OLTC,LEM SPACER BLOCK/AIR GAP',
            'potong_isolasi_fiber' => 'PULLING BOARD,FIXING PART INSULATION',
            'totalHour_coil_making' => '14',
            'totalHour_MouldCasting' => '13',
            'totalHour_CoreCoilAssembly' => '9',
            'hour_coil_lv' => '1',
            'hour_coil_hv' => '3',
            'hour_potong_leadwire' => '1',
            'hour_potong_isolasi' => '6',
            'qc_testing' => null,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('dry_cast_resins')->insert([
            'kd_manhour' => '2',
            'nama_product' => 'Dry Cast Resin',
            'kategori' => '5',
            'nomor_so' => 'SO/TEST',
            'id_fg' => 'FG/TEST',
            'ukuran_kapasitas' => '10',
            'total_hour' => '50',
            'manhour_id' => null,
            'coil_lv' => 'FLAT-KONDUKTOR 1',
            'coil_hv' => 'FLAT-KONDUKTOR 1',
            'potong_leadwire' => 'TEBAL RAIL COPPER = 10T',
            'potong_isolasi' => 'DOG BONE,INNER,OUTER,GANJAL ANTAR SECTION',
            'hv_moulding' => 'KONDUKTOR 1',
            'hv_casting' => '1X PENGISIAN',
            'hv_demoulding' => 'PAKAI AIRWAY STICK',
            'lv_bobbin' => 'PENGECATAN COIL LV & CURING,BUKA BOBIN LV',
            'lv_moulding' => 'SETTING MOULD,MOULDING,CASTING 1 X PROSES PENGISIAN,CASTING 2 X PROSES PENGISIAN',
            'touch_up' => 'HV,LV',
            'type_susun_core' => 'STACKING OUTSOURCHING',
            'wiring' => 'NON-COMPLETE',
            'instal_housing' => 'DENGAN BASE',
            'bongkar_housing' => 'DENGAN BASE',
            'pembuatan_cu_link' => 'HV / LV (STANDARD)',
            'others' => 'PEMBUATAN CU BAR,PEMBUATAN KONEKSI HV,ASSEMBLY,FINISHING',
            'accesories' => 'FAN,OLTC,LEM SPACER BLOCK/AIR GAP',
            'potong_isolasi_fiber' => 'PULLING BOARD,FIXING PART INSULATION',
            'totalHour_coil_making' => '15',
            'totalHour_MouldCasting' => '14',
            'totalHour_CoreCoilAssembly' => '8',
            'hour_coil_lv' => '2',
            'hour_coil_hv' => '4',
            'hour_potong_leadwire' => '2',
            'hour_potong_isolasi' => '7',
            'qc_testing' => null,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('dry_cast_resins')->insert([
            'kd_manhour' => '3',
            'nama_product' => 'Dry Cast Resin',
            'kategori' => '5',
            'nomor_so' => 'SO/TEST',
            'id_fg' => 'FG/TEST',
            'ukuran_kapasitas' => '10',
            'total_hour' => '30',
            'manhour_id' => null,
            'coil_lv' => 'FLAT-KONDUKTOR 1',
            'coil_hv' => 'FLAT-KONDUKTOR 1',
            'potong_leadwire' => 'TEBAL RAIL COPPER = 10T',
            'potong_isolasi' => 'DOG BONE,INNER,OUTER,GANJAL ANTAR SECTION',
            'hv_moulding' => 'KONDUKTOR 1',
            'hv_casting' => '1X PENGISIAN',
            'hv_demoulding' => 'PAKAI AIRWAY STICK',
            'lv_bobbin' => 'PENGECATAN COIL LV & CURING,BUKA BOBIN LV',
            'lv_moulding' => 'SETTING MOULD,MOULDING,CASTING 1 X PROSES PENGISIAN,CASTING 2 X PROSES PENGISIAN',
            'touch_up' => 'HV,LV',
            'type_susun_core' => 'STACKING OUTSOURCHING',
            'wiring' => 'NON-COMPLETE',
            'instal_housing' => 'DENGAN BASE',
            'bongkar_housing' => 'DENGAN BASE',
            'pembuatan_cu_link' => 'HV / LV (STANDARD)',
            'others' => 'PEMBUATAN CU BAR,PEMBUATAN KONEKSI HV,ASSEMBLY,FINISHING',
            'accesories' => 'FAN,OLTC,LEM SPACER BLOCK/AIR GAP',
            'potong_isolasi_fiber' => 'PULLING BOARD,FIXING PART INSULATION',
            'totalHour_coil_making' => '16',
            'totalHour_MouldCasting' => '15',
            'totalHour_CoreCoilAssembly' => '7',
            'hour_coil_lv' => '3',
            'hour_coil_hv' => '5',
            'hour_potong_leadwire' => '3',
            'hour_potong_isolasi' => '8',
            'qc_testing' => null,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('dry_cast_resins')->insert([
            'kd_manhour' => '4',
            'nama_product' => 'Dry Cast Resin',
            'kategori' => '5',
            'nomor_so' => 'SO/TEST',
            'id_fg' => 'FG/TEST',
            'ukuran_kapasitas' => '10',
            'total_hour' => '20',
            'manhour_id' => null,
            'coil_lv' => 'FLAT-KONDUKTOR 1',
            'coil_hv' => 'FLAT-KONDUKTOR 1',
            'potong_leadwire' => 'TEBAL RAIL COPPER = 10T',
            'potong_isolasi' => 'DOG BONE,INNER,OUTER,GANJAL ANTAR SECTION',
            'hv_moulding' => 'KONDUKTOR 1',
            'hv_casting' => '1X PENGISIAN',
            'hv_demoulding' => 'PAKAI AIRWAY STICK',
            'lv_bobbin' => 'PENGECATAN COIL LV & CURING,BUKA BOBIN LV',
            'lv_moulding' => 'SETTING MOULD,MOULDING,CASTING 1 X PROSES PENGISIAN,CASTING 2 X PROSES PENGISIAN',
            'touch_up' => 'HV,LV',
            'type_susun_core' => 'STACKING OUTSOURCHING',
            'wiring' => 'NON-COMPLETE',
            'instal_housing' => 'DENGAN BASE',
            'bongkar_housing' => 'DENGAN BASE',
            'pembuatan_cu_link' => 'HV / LV (STANDARD)',
            'others' => 'PEMBUATAN CU BAR,PEMBUATAN KONEKSI HV,ASSEMBLY,FINISHING',
            'accesories' => 'FAN,OLTC,LEM SPACER BLOCK/AIR GAP',
            'potong_isolasi_fiber' => 'PULLING BOARD,FIXING PART INSULATION',
            'totalHour_coil_making' => '17',
            'totalHour_MouldCasting' => '20',
            'totalHour_CoreCoilAssembly' => '6',
            'hour_coil_lv' => '4',
            'hour_coil_hv' => '6',
            'hour_potong_leadwire' => '4',
            'hour_potong_isolasi' => '9',
            'qc_testing' => null,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('dry_cast_resins')->insert([
            'kd_manhour' => '5',
            'nama_product' => 'Dry Cast Resin',
            'kategori' => '5',
            'nomor_so' => 'SO/TEST',
            'id_fg' => 'FG/TEST',
            'ukuran_kapasitas' => '10',
            'total_hour' => '15',
            'manhour_id' => null,
            'coil_lv' => 'FLAT-KONDUKTOR 1',
            'coil_hv' => 'FLAT-KONDUKTOR 1',
            'potong_leadwire' => 'TEBAL RAIL COPPER = 10T',
            'potong_isolasi' => 'DOG BONE,INNER,OUTER,GANJAL ANTAR SECTION',
            'hv_moulding' => 'KONDUKTOR 1',
            'hv_casting' => '1X PENGISIAN',
            'hv_demoulding' => 'PAKAI AIRWAY STICK',
            'lv_bobbin' => 'PENGECATAN COIL LV & CURING,BUKA BOBIN LV',
            'lv_moulding' => 'SETTING MOULD,MOULDING,CASTING 1 X PROSES PENGISIAN,CASTING 2 X PROSES PENGISIAN',
            'touch_up' => 'HV,LV',
            'type_susun_core' => 'STACKING OUTSOURCHING',
            'wiring' => 'NON-COMPLETE',
            'instal_housing' => 'DENGAN BASE',
            'bongkar_housing' => 'DENGAN BASE',
            'pembuatan_cu_link' => 'HV / LV (STANDARD)',
            'others' => 'PEMBUATAN CU BAR,PEMBUATAN KONEKSI HV,ASSEMBLY,FINISHING',
            'accesories' => 'FAN,OLTC,LEM SPACER BLOCK/AIR GAP',
            'potong_isolasi_fiber' => 'PULLING BOARD,FIXING PART INSULATION',
            'totalHour_coil_making' => '18',
            'totalHour_MouldCasting' => '17',
            'totalHour_CoreCoilAssembly' => '5',
            'hour_coil_lv' => '5',
            'hour_coil_hv' => '7',
            'hour_potong_leadwire' => '5',
            'hour_potong_isolasi' => '10',
            'qc_testing' => null,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
    }
}
